In [124]:
import pandas as pd
import numpy as np

In [125]:
temp_df = pd.read_csv(
    'IMDB Dataset.csv',
    engine='python',
    sep=',', #Columns are separated by commas.
    quotechar='"',  #Text inside double quotes " " is one field.
    on_bad_lines='skip' #If pandas finds a corrupted row like: "This movie was great,positive
)
# engine='python'
# Pandas has 2 parsers:
# "c" → Fast but strict (default)
# "python" → Slower but flexible

In [126]:
df=temp_df.iloc[:10000]

In [127]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [128]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [129]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [130]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [131]:
df.duplicated().sum()

np.int64(17)

In [132]:
df.drop_duplicates(inplace=True)

/tmp/ipython-input-3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [133]:
df.duplicated().sum()

np.int64(0)

In [134]:
import re
def remove_tags(raw_text):
  cleaned_text=re.sub(re.compile('<.*>'),'',raw_text) #find pattenrn replace with somthing re.sub(pattern, replace_with, text)
  return cleaned_text

In [135]:
df['review']=df['review'].apply(remove_tags)

/tmp/ipython-input-2928534252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)

In [136]:
df['review'][1]

"A wonderful little production. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done."

In [137]:
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The realism rea...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [138]:
df['review']=df['review'].apply(lambda x:x.lower())

/tmp/ipython-input-2697927567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())

In [139]:
df['review'][1]

"a wonderful little production. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell's murals decorating every surface) are terribly well done."

In [140]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [141]:
sw_list = stopwords.words('english')

df['review'] = df['review'].apply(
    lambda x: [item for item in x.split() if item not in sw_list]
)

/tmp/ipython-input-97121717.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(

In [142]:
df

                                                 review sentiment
0     [one, reviewers, mentioned, watching, 1, oz, e...  positive
1     [wonderful, little, production., realism, real...  positive
2     [thought, wonderful, way, spend, time, hot, su...  positive
3     [basically, there's, family, little, boy, (jak...  negative
4     [petter, mattei's, "love, time, money", visual...  positive
...                                                 ...       ...
9995  [fun,, entertaining, movie, wwii, german, spy,...  positive
9996  [give, break., anyone, say, "good, hockey, mov...  negative
9997  [movie, bad, movie., watching, endless, series...  negative
9998  [movie, probably, made, entertain, middle, sch...  negative
9999  [smashing, film, film-making., shows, intense,...  positive

[9983 rows x 2 columns]

In [143]:
X=df.iloc[:,0:1]
Y=df['sentiment']

In [144]:
X

                                                 review
0     [one, reviewers, mentioned, watching, 1, oz, e...
1     [wonderful, little, production., realism, real...
2     [thought, wonderful, way, spend, time, hot, su...
3     [basically, there's, family, little, boy, (jak...
4     [petter, mattei's, "love, time, money", visual...
...                                                 ...
9995  [fun,, entertaining, movie, wwii, german, spy,...
9996  [give, break., anyone, say, "good, hockey, mov...
9997  [movie, bad, movie., watching, endless, series...
9998  [movie, probably, made, entertain, middle, sch...
9999  [smashing, film, film-making., shows, intense,...

[9983 rows x 1 columns]

In [145]:
Y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [146]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
Y=encoder.fit_transform(Y)

In [147]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [148]:
from sklearn.model_selection import train_test_split

In [149]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [150]:
X_train.shape

(7986, 1)

In [151]:
X_test.shape

(1997, 1)

In [152]:
#Apply Bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [153]:
cv=CountVectorizer()

In [154]:
X_train['review'] = X_train['review'].apply(lambda x: " ".join(x))
X_test['review'] = X_test['review'].apply(lambda x: " ".join(x))

In [155]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [156]:
X_train_bow.shape

(7986, 37238)

In [157]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [158]:
y_pred=gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test,y_pred)

0.6204306459689535

In [159]:
confusion_matrix(y_test,y_pred)

array([[723, 262],
       [496, 516]])

In [160]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [161]:
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8197295943915874

In [162]:
import joblib
joblib.dump(rf, "rf_model.pkl")

['rf_model.pkl']

In [164]:
from google.colab import files

files.download("rf_model.pkl")

In [70]:
cv=CountVectorizer(max_features=3000)
x_train_bow=cv.fit_transform(X_train['review']).toarray()
x_test_bow=cv.fit_transform(X_test['review']).toarray()
rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [71]:
y_pred=rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.5408112168252378

In [72]:
cv=CountVectorizer(ngram_range=(1,2))
x_train_bow=cv.fit_transform(X_train['review']).toarray()
x_test_bow=cv.fit_transform(X_test['review']).toarray()

In [74]:
rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)

RandomForestClassifier()

In [75]:
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8197295943915874

In [76]:
cv=CountVectorizer(ngram_range=(1,2),max_features=5000)
x_train_bow=cv.fit_transform(X_train['review']).toarray()
x_test_bow=cv.fit_transform(X_test['review']).toarray()

In [77]:
rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)

RandomForestClassifier()

In [78]:
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8167250876314471

In [81]:
#Using TDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [82]:
tfidf=TfidfVectorizer()

In [83]:
x_train_bow=tfidf.fit_transform(X_train['review']).toarray()
x_test_bow=tfidf.fit_transform(X_test['review']).toarray()

In [84]:
rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [86]:
y_pred=rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

ValueError: X has 18888 features, but RandomForestClassifier is expecting 37238 features as input.

In [87]:
df

                                                 review sentiment
0     [one, reviewers, mentioned, watching, 1, oz, e...  positive
1     [wonderful, little, production., realism, real...  positive
2     [thought, wonderful, way, spend, time, hot, su...  positive
3     [basically, there's, family, little, boy, (jak...  negative
4     [petter, mattei's, "love, time, money", visual...  positive
...                                                 ...       ...
9995  [fun,, entertaining, movie, wwii, german, spy,...  positive
9996  [give, break., anyone, say, "good, hockey, mov...  negative
9997  [movie, bad, movie., watching, endless, series...  negative
9998  [movie, probably, made, entertain, middle, sch...  negative
9999  [smashing, film, film-making., shows, intense,...  positive

[9983 rows x 2 columns]

In [89]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 22.2 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [90]:
import gensim

In [92]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [93]:
story=[]
for doc in df['review']:
  raw_sent=sent_tokenize(doc)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

In [94]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [97]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

TypeError: expected string or bytes-like object, got 'list'

In [100]:
import nltk
nltk.download('punkt', download_dir='/usr/local/nltk_data')
nltk.download('punkt_tab', download_dir='/usr/local/nltk_data')

[nltk_data] Downloading package punkt to /usr/local/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /usr/local/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [104]:
story = []
df['review'] = df['review'].apply(lambda x: " ".join(x))
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

/tmp/ipython-input-3795868449.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: " ".join(x))

In [106]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [109]:
model.build_vocab(story)

In [110]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(3326923, 3572475)

In [111]:
len(model.wv.index_to_key)

23826

In [113]:
import numpy as np

def document_vector(doc):
    words = [word for word in doc.split() if word in model.wv.index_to_key]

    if len(words) == 0:
        return np.zeros(model.vector_size)

    return np.mean(model.wv[words], axis=0)

In [114]:
document_vector(df['review'].values[0])

array([-1.1593779e-01,  2.7863625e-01,  1.0649018e-01,  9.7131208e-02,
        2.0620784e-01, -6.4052820e-01,  1.8627194e-01,  8.3143377e-01,
       -3.8266051e-01, -3.0702472e-01, -9.2420056e-02, -6.5035576e-01,
        1.2646562e-01,  2.6317555e-01,  2.3171017e-01, -2.2128461e-02,
        1.8501505e-01, -4.4663182e-01, -4.8457831e-02, -8.5877454e-01,
        1.9747913e-01,  5.9308171e-02,  1.9835581e-01, -4.0331033e-01,
       -8.0623388e-02, -1.6354457e-01, -3.3557153e-01, -2.5244272e-01,
       -4.4451526e-01,  1.9312935e-02,  5.0215977e-01, -3.3863582e-02,
        2.1215773e-01, -3.1414664e-01, -1.0320302e-01,  6.0551888e-01,
        7.3883869e-02, -5.0513583e-01, -3.5435417e-01, -9.6315807e-01,
        1.9235028e-01, -5.3262526e-01, -1.6727170e-01,  2.5802925e-02,
        2.5630897e-01, -2.5623780e-01, -4.9477264e-01, -8.7026201e-02,
        8.5934855e-02,  1.2556727e-01,  1.1625686e-01, -4.1041785e-01,
       -5.3297706e-02, -1.3732991e-02, -2.5982013e-01,  2.1402270e-01,
        4.5076013e-01,  6.6166602e-02, -4.4267088e-01,  1.4312254e-01,
        1.1566808e-01,  6.5365096e-04, -1.0911718e-01,  2.6976705e-02,
       -5.9455878e-01,  3.2299426e-01,  3.7858631e-02,  3.1202003e-01,
       -6.1135429e-01,  5.3547466e-01, -3.2617363e-01,  3.4661725e-02,
        6.1677235e-01, -2.1794347e-01,  5.1446557e-01,  1.4841843e-01,
        4.8389316e-02,  1.5883188e-01, -1.7163093e-01,  8.7909304e-02,
       -2.6481283e-01,  1.2740952e-02, -3.0646735e-01,  5.4305977e-01,
       -1.8514414e-01, -1.1812694e-02,  4.6471089e-02,  4.2637610e-01,
        6.0779184e-01,  2.7411678e-01,  2.4585791e-01,  1.6110550e-01,
        1.5614632e-01,  1.5949580e-01,  7.8869510e-01,  4.5967507e-01,
        2.3601662e-01, -6.7776412e-01,  3.1182325e-01, -1.4688423e-01],
      dtype=float32)

In [115]:
from tqdm import tqdm

In [117]:
X=[]
for doc in tqdm(df['review'].values):
  X.append(document_vector(doc))

100%|██████████| 9983/9983 [04:05<00:00, 40.70it/s]

In [ ]:
X=np.array(X)
X.shape

In [118]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [121]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [122]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6404606910365548

In [123]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7110665998998498